---
apiVersion: v1
kind: Namespace
metadata:
  name: phonie-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airtime
  labels:
    app: airtime
  namespace: phonie-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airtime
      
  template:
    metadata:
      labels:
        app: airtime
        
    spec:
      containers:
      - name: airtime
        image: rtmabiola/phonie-app:v1
        resources:
          limits:
            memory: "200Mi"
            cpu: "300m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: airtime-service
  labels:
    app: airtime
  namespace: phonie-app
spec:
  type: LoadBalancer
  selector:
    app: airtime
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30100

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: phonie-app
type: Opaque
data:
  mongo-root-username: bW9uZ29kYi1hZG1pbg==
  mongo-root-password: cmtrZHllMjQhZA==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
  namespace: phonie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB-ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username 
        - name: MONGO_INITDB-ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password 

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: phonie-app
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: phonie-app
data:
  database_url: mongodb-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: phonie-app
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:0.54.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username 
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password 
        - name: ME_CONFIG_MONGODB_SERVER 
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
            
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: phonie-app
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 32220